### ISSUE TITLE
Contribute plugin upstream?

### ISSUE THREAD

**Issue by zultron** [benzrf/pyglossary-cc-cedict#2]
Thanks for writing this plugin!  Are there any plans to contribute it upstream?  It seems obvious that pyglossary should support StarDict format out of the box.

**Comment by sarahzrf** [comment]
It does! This plugin is just for importing from [CC-CEDICT](https://cc-cedict.org/wiki/), which is an open Chinese dictionary.

**Comment by zultron** [comment]
Duh, that's actually what I meant.  I'm converting CC-CEDICT (and the canto version) for GoldenDict.

I meant to say, "It seems obvious that pyglossary should support CC-CEDICT format out of the box."  Any plans to contribute the plugin upstream?

**Comment by sarahzrf** [comment]
That seems reasonable—I can't actually remember why I hadn't already done that. Let me go make a PR :)

**Comment by sarahzrf** [comment]
https://github.com/ilius/pyglossary/pull/141
